---
Name: mandrill
After:
  - 'framework/*'
  - 'cms/*'
---
MandrillMailer:
  default_params:
    preserve_recipients: false
    inline_css: true
  subaccount: null
  global_tags: []
MandrillAdmin:
  cache_enabled: true