---
Name: mandrill
After:
  - 'framework/*'
  - 'cms/*'
---
Director:
  rules:
    'mandrill//$Action/$ID/$Name': 'MandrillController'
MandrillMailer:
  default_params:
    preserve_recipients: false
    inline_css: true
  subaccount: null
  global_tags: []
  use_google_analytics: true
  name_fallback: true
MandrillAdmin:
  cache_enabled: true
MandrillEmail:
  default_theme: 'dark'
  templates:
    - BasicEmail
    - BoilerplateEmail
    - LogoEmail
  themes:
    dark:
      header_color: '#333333'
      header_font_color: '#ffffff'
      footer_color: '#ebebeb'
      footer_font_color: '#333333'
      panel_color: '#ECF8FF'
      panel_border_color: '#b9e5ff'
      panel_font_color: '#000000'
    light:
      header_color: '#eeeeee'
      header_font_color: '#333333'
      footer_color: '#ebebeb'
      footer_font_color: '#333333'
      panel_color: '#ECF8FF'
      panel_border_color: '#b9e5ff'
      panel_font_color: '#000000'
    blue:
      header_color: '#eeeeee'
      header_font_color: '#6c737b'
      footer_color: '#ebebeb'
      footer_font_color: '#333333'
      panel_color: '#00afcb'
      panel_border_color: '#008ea5'
      panel_font_color: '#ffffff'
EmailTemplate:
  allow_configure_theme: false
  allow_configure_template: false
EmailImportTask:
  ignored_modules: ['framework','cms','mandrill']
---
Only:
  classexists: 'Fluent'
---
EmailTemplate:
  extensions:
    - FluentExtension